config/routes.rb
Forvalid::Application.routes.draw do
  namespace :admin do
    resources :products
  end

  scope '/list' do
    resources :users
  end

  resources :users, only: [:index, :show]

  resources :microposts do
    resources :comments
    
    collection do
      get 'search'
    end
  end

  get 'test/index'

  match 'select' => 'test#index', as: :select_of_data
  match 'posts/new' => 'microposts#new'
  match 'posts/:id' => 'microposts#show'
  match 'posts/:id/edit' => 'microposts#edit'

  match '/posts' => redirect('/microposts')

  match 'posts/*trash/:id' => 'microposts#show'
  

end

app/models/admin/product.rb
# == Schema Information
#
# Table name: admin_products
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)
#  code       :string(255)
#  type       :string(255)
#  desc       :text
#  created_at :datetime
#  updated_at :datetime
#

class Admin::Product < ActiveRecord::Base
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  # GET /admin/products
  # GET /admin/products.xml
  def index
    @admin_products = Admin::Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admin_products }
    end
  end

  # GET /admin/products/1
  # GET /admin/products/1.xml
  def show
    @admin_product = Admin::Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_product }
    end
  end

  # GET /admin/products/new
  # GET /admin/products/new.xml
  def new
    @admin_product = Admin::Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_product }
    end
  end

  # GET /admin/products/1/edit
  def edit
    @admin_product = Admin::Product.find(params[:id])
  end

  # POST /admin/products
  # POST /admin/products.xml
  def create
    @admin_product = Admin::Product.new(params[:admin_product])

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to(@admin_product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @admin_product, :status => :created, :location => @admin_product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin_product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/products/1
  # PUT /admin/products/1.xml
  def update
    @admin_product = Admin::Product.find(params[:id])

    respond_to do |format|
      if @admin_product.update_attributes(params[:admin_product])
        format.html { redirect_to(@admin_product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.xml
  def destroy
    @admin_product = Admin::Product.find(params[:id])
    @admin_product.destroy

    respond_to do |format|
      format.html { redirect_to(admin_products_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for(@admin_product) do |f| %>
  <% if @admin_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul>
      <% @admin_product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing admin_product</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_product %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<h1>Listing admin_products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Code</th>
    <th>Type</th>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_products.each do |admin_product| %>
  <tr>
    <td><%= admin_product.name %></td>
    <td><%= admin_product.code %></td>
    <td><%= admin_product.type %></td>
    <td><%= admin_product.desc %></td>
    <td><%= link_to 'Show', admin_product %></td>
    <td><%= link_to 'Edit', edit_admin_product_path(admin_product) %></td>
    <td><%= link_to 'Destroy', admin_product, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New admin_product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @admin_product.name %>
</p>

<p>
  <b>Code:</b>
  <%= @admin_product.code %>
</p>

<p>
  <b>Type:</b>
  <%= @admin_product.type %>
</p>

<p>
  <b>Desc:</b>
  <%= @admin_product.desc %>
</p>


<%= link_to 'Edit', edit_admin_product_path(@admin_product) %> |
<%= link_to 'Back', admin_products_path %>